/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://2rbubvupsncjba6cbogz42jegq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4mhfwl7nbzf75gwnagq76uvme4",
    "aws_cognito_identity_pool_id": "ap-southeast-1:65cc705b-6b83-439d-801d-f9881639b429",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_kh0qNqAsG",
    "aws_user_pools_web_client_id": "5o21bko88366a535i3l1hs7sj",
    "oauth": {},
    "aws_user_files_s3_bucket": "kachuwa-image192225-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
